### ISSUE TITLE
Get (GET) user

### ISSUE THREAD

**Issue by JoergWolff** [JoergWolff/pensioner-times#3]
## Value Proposition

**As a** User 
**I want to** see all users in the libary.
**so that** i can find my profile.

## Description

Implemen a feature to display each user in a card in a libary.

## Acceptance Criteria

- [x] Create a GET enpoint "/api/users" to receive all users.
- [x] Create a route "/user" to display all users.
- [x] The list of user should displayed on the frontend.

## Tasks

- [x] Create a model for hobby with "id, name, isActive, createdAt, updatedAt"
- [x] Create a model for user with "id, firstname, lastname, email, hobby[], isActive, createdAt, updatedAt
- [x] Create a "UserController" in the backend with @GetMapping.
- [x] Create a "UserService" in the backend for validation.
- [x] Create a "UserRepository" in the backend for managing database request.
- [x] Create a component UserGallery to display all users.
- [x] Create a navigation component and a link in it to UserGallery.
- [x] Implement unit and integration tests.
- [x] Add some styling

## Complexity

M

**Comment by JoergWolff** [comment]
Donw
