### ISSUE TITLE
Add (POST) user

### ISSUE THREAD

**Issue by JoergWolff** [JoergWolff/pensioner-times#4]
## Value Proposition

**As a** User 
**I want to** add my profiledata to a libary
**so that** I can see my profie on the libary

## Description

Implement a feature that allows user to add their own profile to a global libary for all members.

## Acceptance Criteria

- [ ] Create a POST endpoint "/api/users" to add new user to the backend. The user was saved in a database.
- [ ] Create a route "/user/add" to display a form for add a new user.
- [ ] The added user should be displayed in a list of users.

## Tasks

- [ ] Create a "UserController" in the backend with @PostMapping.
- [ ] Create a "UserService" in the backend for validation.
- [ ] Create a "UserRepository" in the backen for managing database request.
- [ ] Create a navigation link on the homepage.
- [ ] Create a new component with a form to input a new user.
- [ ] Create a POST request to send user data to the backend.
- [ ] Implement unit and integration tests.

## Complexity

S
