### ISSUE TITLE
Get (GET) user

### ISSUE THREAD

**Issue by JoergWolff** [JoergWolff/pensioner-times#5]
## Value Proposition

**As a** User 
**I want to** see all users in the libary.
**so that** i can find my profile.

## Description

Implemen a feature to display each user in a card in a libary.

## Acceptance Criteria

- [ ] Create a GET enpoint "/api/users" to receive all users.
- [ ] Create a route "/user" to display all users.
- [ ] The list of user should displayed on the frontend.

## Tasks

- [ ] Create a model for hobby with "id, name, isActive, createdAt, updatedAt"
- [ ] Create a model for user with "id, firstname, lastname, email, hobby[], isActive, createdAt, updatedAt
- [ ] Create a "UserController" in the backend with @GetMapping.
- [ ] Create a "UserService" in the backend for validation.
- [ ] Create a "UserRepository" in the backend for managing database request.
- [ ] Create a component UserGallery to display all users.
- [ ] Create a navigation component and a link in it to UserGallery.
- [ ] Add some styling

## Complexity

M
